
GET http://localhost:3000/schools/all
###
GET http://localhost:3000/schools/MIU
###
GET http://localhost:3000/schools/MIU/courses
###
GET http://localhost:3000/schools/MIU/courses/CS123
###
GET http://localhost:3000/schools/MIU/teachers
###
GET http://localhost:3000/schools/MIU/students
###
POST http://localhost:3000/schools/MIU/teachers/new 
content-type: application/json

{ "id": "321", "name": "Keith", "department": "Art" } 
###
DELETE  http://localhost:3000/schools/MIU/teachers/321
###
PATCH http://localhost:3000/schools/MIU/teachers/321
content-type: application/json

{ "name": "Beith Levi" } 

###
POST http://localhost:3000/schools/MIU/courses/CS123
content-type: application/json

{ "id": "333", "name": "Fathi", "degree": "graduate" } 
###

PATCH http://localhost:3000/schools/MIU/students/333
content-type: application/json

{ "name": "Fathi Aswad" }
###
PATCH http://localhost:3000/schools/MIU/courses/CS123/students/333
content-type: application/json

{"grade": "94"}
###
DELETE http://localhost:3000/schools/MIU/courses/CS123/students/333

#####################################################################
#####################INITIALIZE/CLEAR DATABASE#######################
#####################################################################
POST http://localhost:3000/schools/fill HTTP/1.1
content-type: application/json

[{
  "name": "MIU",
  "teachers": [
    { "id": "123", "name": "Asaad", "department": "Computer Science" },
    { "id": "456", "name": "Umur", "department": "Computer Science" }
  ],
  "courses": [
    {
      "id": "CS123",
      "title": "Modern Web Applicatons",
      "students": [
        { "id": "111", "name": "John", "degree": "undergraduate" },
        { "id": "222", "name": "Selin", "degree": "undergraduate" }
      ]
    },
    {
      "id": "CS456",
      "title": "Big Data",
      "students": [
        { "id": "111", "name": "John", "degree": "undergraduate" },
        { "id": "222", "name": "Selin", "degree": "undergraduate" }
      ]
    },
    {
      "id": "CS789",
      "title": "Software Architecture",
      "students": [
        { "id": "111", "name": "John", "degree": "undergraduate" },
        { "id": "222", "name": "Selin", "degree": "undergraduate" }
      ]
    }
  ]
}]
###

DELETE http://localhost:3000/schools/clear HTTP/1.1

###